### ISSUE TITLE
Not a valid site error

### ISSUE THREAD

**Issue by kadnan** [juliomalegria/python-craigslist#10]
None of your example is working, gives errors like:

```
'newyork' is not a valid site
Traceback (most recent call last):
  File "/Clients/AlexanderPrince/cl.py", line 3, in <module>
    cl_e = CraigslistEvents(site='newyork', filters={'free': True, 'food': True})
  File "/Library/Python/2.7/site-packages/craigslist/__init__.py", line 67, in __init__
    raise ValueError(msg)
ValueError: 'newyork' is not a valid site
```

**Comment by aemonm** [comment]
Also having the same issue.

**Comment by kggiorno** [comment]
From current version of __init__.py starting at line 66:

def __init__(self, site='sfbay', area=None, category=None, filters=None,
                 log_level=logging.WARNING):

        self.set_logger(log_level)

        **if site not in all_sites:
            msg = "'%s' is not a valid site" % site
            logger.error(msg)
            raise ValueError(msg)**
        self.site = site

So this is failing because the site value (even if we leave out a site value the class default fails with the same error) is not in the all_sites variable. If we look higher up in the code, around line 23, we see:

# Global
all_sites = get_all_sites()  # All the Craiglist sites

Seems like get_all_sites() is failing to initialize the all_sites var. Just above, line 16, we see:

from .sites import get_all_sites

Trying to test this import and have been failing with:

SystemError: Parent module '' not loaded, cannot perform relative import

Looks like sites module doesn't exist in my python 3.4.3 sys modules

**Comment by juliomalegria** [comment]
New version of python-craigslist (1.0.1) is live in PyPI now. That version should fix this issue.

Thanks for bearing with me :)
